### ISSUE TITLE
Add a version page

### ISSUE THREAD

**Issue by ShipsWithCannons** [skiwi2/OLog#7]
There should be a page with general information about the server. This should at least include the version of the project it's running.

In time this page can be expanded if required.

**Comment by skiwi2** [comment]
The version of the project is the following:
- major.minor.hotfix version
- latest commit hash

When building a WAR, the latest commit hash should be stored somewhere in the WAR file.

**Comment by skiwi2** [comment]
This has been implemented in a2584a80c71dcfdd0d3337347fd74baa8e2441ea.
